os: Visual Studio 2015

platform: x64

environment:
  MSVC_DEFAULT_OPTIONS: ON
  MINICONDA: "C:\\Miniconda36-x64"
  MAKE_FLAGS: ""
  MSVC: 1

configuration: Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - cmd: git submodule update --init --recursive
  - ps: wget https://bitbucket.org/eigen/eigen/get/1f0f8337c029.zip -OutFile eigen.zip
  - cmd: 7z x eigen.zip -o"C:\projects" -y > nul
  - cmd: rename C:\projects\eigen-eigen-1f0f8337c029 eigen
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;C:\Program Files (x86)\Pandoc;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=3.6 cython numpy
  - activate test-env

before_build:
  - cmd: git clone https://github.com/clab/dynet
  - ps: "(gc dynet/setup.py) -replace '. (version=.)0.0.0', '${1}3.dev1' | Out-File -encoding 'UTF8' dynet/setup.py"
  - cmd: md dynet\build
  - cmd: cd dynet\build
  - cmd: cmake -DEIGEN3_INCLUDE_DIR=C:/projects/eigen -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=%configuration% -DPYTHON=python.exe ..
  - cmd: set VS90COMNTOOLS=%VS140COMNTOOLS%
  - cmd: cd ..\..

build:
  parallel: true
  project: dynet\build\dynet.sln
  verbosity: normal

after_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%/dynet/build/python
  - python ../../setup.py EIGEN3_INCLUDE_DIR=C:/projects/eigen build --build-dir=.. --skip-build install
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - python setup.py install

test_script:
  - python -m unittest discover -v
