cache: apt
sudo: false
language: python
cache:
  pip: true
  directories:
  - $HOME/miniconda
  - dynet
python:
  - "3.5"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libstdc++6
    - gcc-4.8
    - g++-4.8
    - cmake
    - mercurial
    - libboost-filesystem1.55-dev
    - libboost-program-options1.55-dev
    - libboost-serialization1.55-dev
    - libboost-test1.55-dev
    - libboost-regex1.55-dev
before_install:
  - ci/install-miniconda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - ci/install-prerequisites.sh
install:
  - python setup.py install
before_script:
  - mkdir pickle
  - curl -L http://www.cs.huji.ac.il/~danielh/ucca/ucca_corpus_pickle.tgz | tar xz -C pickle
  - python ucca/scripts/split_corpus.py pickle -t 4282 -d 454 -l
  - wget http://amr.isi.edu/download/2016-03-14/alignment-release-{training,dev,test}-bio.txt
env:
  - TEST_SUITE=unit
  - TEST_SUITE=sparse-ucca
  - TEST_SUITE=mlp-ucca
  - TEST_SUITE=bilstm-ucca
  - TEST_SUITE=noop-ucca
  - TEST_SUITE=tune-ucca
  - TEST_SUITE=noop-amr
  - TEST_SUITE=convert-amr
script:
  - ci/test.sh
