cache: apt
sudo: false
language: python
python:
  - "3.5"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libstdc++6
    - gcc-4.8
    - g++-4.8
    - cmake
    - mercurial
    - libboost-filesystem1.55-dev
    - libboost-program-options1.55-dev
    - libboost-serialization1.55-dev
    - libboost-test1.55-dev
    - libboost-regex1.55-dev
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH" CXX="g++-4.8" CC="gcc-4.8" MAKE_FLAGS="-j 1"
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy libgcc
  - pip install pytest-pep8
  - pip install -r requirements.txt
  - python -m spacy download en
install:
  - python setup.py install
before_script:
  - mkdir pickle
  - curl -L http://www.cs.huji.ac.il/~danielh/ucca/ucca_corpus_pickle.tgz | tar xz -C pickle
  - python ucca/scripts/split_corpus.py pickle -t 4282 -d 454 -l
env:
  - TEST_SUITE=unit
  - TEST_SUITE=sparse
  - TEST_SUITE=dense
  - TEST_SUITE=mlp
  - TEST_SUITE=bilstm
  - TEST_SUITE=tune
script:
  - ci/test.sh
