cache: apt
dist: trusty
sudo: false
language: python
cache:
  pip: true
  directories:
  - $HOME/virtualenv
  - $HOME/nltk_data
python:
  - "3.6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - g++-6
    - libstdc++6
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-serialization-dev
    - libboost-test-dev
    - libboost-regex-dev
    - pandoc
install:
  - export CXX=g++-6 CC=gcc-6 MAKE_FLAGS="-j 2"
  - python setup.py install
before_script:
  - mkdir pickle
  - curl -L http://www.cs.huji.ac.il/~danielh/ucca/ucca_corpus_pickle.tgz | tar xz -C pickle
  - python -m scripts.split_corpus -q pickle -t 4282 -d 454 -l
  - curl --remote-name-all https://amr.isi.edu/download/2016-03-14/alignment-release-{training,dev,test}-bio.txt
  - python scheme/split.py -q alignment-release-training-bio.txt alignment-release-training-bio
env:
  - TEST_SUITE=unit
  - TEST_SUITE=sparse-ucca
  - TEST_SUITE=mlp-ucca
  - TEST_SUITE=bilstm-ucca
  - TEST_SUITE=noop-ucca
  - TEST_SUITE=tune-ucca
  - TEST_SUITE=sparse-amr
  - TEST_SUITE=noop-amr
  - TEST_SUITE=convert-amr
script:
  - ci/test.sh
