cache: apt
dist: trusty
sudo: false
language: python
cache:
  pip: true
  directories:
  - $HOME/virtualenv
python:
  - "3.6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - libstdc++6
    - pandoc
install:
  - export CXX=g++-6 CC=gcc-6 MAKE_FLAGS="-j 2"
  - python setup.py install
env:
  - TEST_SUITE=unit
  - TEST_SUITE=sparse-ucca
  - TEST_SUITE=mlp-ucca
  - TEST_SUITE=bilstm-ucca
  - TEST_SUITE=noop-ucca
  - TEST_SUITE=tune-ucca
  - TEST_SUITE=sparse-amr
  - TEST_SUITE=noop-amr
  - TEST_SUITE=convert-amr
  - TEST_SUITE=sparse-sdp
  - TEST_SUITE=mlp-sdp
  - TEST_SUITE=bilstm-sdp
  - TEST_SUITE=noop-sdp
  - TEST_SUITE=convert-sdp
script:
  - ci/test.sh
